// <auto-generated />
using System;
using IslamicFace.Infrastructure.context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IslamicFace.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250726131354_MergedOfAllMigrations")]
    partial class MergedOfAllMigrations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IslamicFace.Domain.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("Int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CountryId")
                        .HasColumnType("Int");

                    b.Property<string>("Name_ARB")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("Name_ENG")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("VARCHAR");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Cities", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryId = 1,
                            Name_ARB = "القاهرة",
                            Name_ENG = "Cairo"
                        },
                        new
                        {
                            Id = 2,
                            CountryId = 1,
                            Name_ARB = "الجيزة",
                            Name_ENG = "Giza"
                        },
                        new
                        {
                            Id = 3,
                            CountryId = 1,
                            Name_ARB = "الإسكندرية",
                            Name_ENG = "Alexandria"
                        },
                        new
                        {
                            Id = 4,
                            CountryId = 1,
                            Name_ARB = "الدقهلية",
                            Name_ENG = "Dakahlia"
                        },
                        new
                        {
                            Id = 5,
                            CountryId = 1,
                            Name_ARB = "البحر الأحمر",
                            Name_ENG = "Red Sea"
                        },
                        new
                        {
                            Id = 6,
                            CountryId = 1,
                            Name_ARB = "البحيرة",
                            Name_ENG = "Beheira"
                        },
                        new
                        {
                            Id = 7,
                            CountryId = 1,
                            Name_ARB = "الفيوم",
                            Name_ENG = "Fayoum"
                        },
                        new
                        {
                            Id = 8,
                            CountryId = 1,
                            Name_ARB = "الغربية",
                            Name_ENG = "Gharbia"
                        },
                        new
                        {
                            Id = 9,
                            CountryId = 1,
                            Name_ARB = "الإسماعيلية",
                            Name_ENG = "Ismailia"
                        },
                        new
                        {
                            Id = 10,
                            CountryId = 1,
                            Name_ARB = "المنوفية",
                            Name_ENG = "Monufia"
                        },
                        new
                        {
                            Id = 11,
                            CountryId = 1,
                            Name_ARB = "المنيا",
                            Name_ENG = "Minya"
                        },
                        new
                        {
                            Id = 12,
                            CountryId = 1,
                            Name_ARB = "القليوبية",
                            Name_ENG = "Qaliubiya"
                        },
                        new
                        {
                            Id = 13,
                            CountryId = 1,
                            Name_ARB = "الوادي الجديد",
                            Name_ENG = "New Valley"
                        },
                        new
                        {
                            Id = 14,
                            CountryId = 1,
                            Name_ARB = "السويس",
                            Name_ENG = "Suez"
                        },
                        new
                        {
                            Id = 15,
                            CountryId = 1,
                            Name_ARB = "أسوان",
                            Name_ENG = "Aswan"
                        },
                        new
                        {
                            Id = 16,
                            CountryId = 1,
                            Name_ARB = "أسيوط",
                            Name_ENG = "Asyut"
                        },
                        new
                        {
                            Id = 17,
                            CountryId = 1,
                            Name_ARB = "بني سويف",
                            Name_ENG = "Beni Suef"
                        },
                        new
                        {
                            Id = 18,
                            CountryId = 1,
                            Name_ARB = "بورسعيد",
                            Name_ENG = "Port Said"
                        },
                        new
                        {
                            Id = 19,
                            CountryId = 1,
                            Name_ARB = "دمياط",
                            Name_ENG = "Damietta"
                        },
                        new
                        {
                            Id = 20,
                            CountryId = 1,
                            Name_ARB = "سوهاج",
                            Name_ENG = "Sohag"
                        },
                        new
                        {
                            Id = 21,
                            CountryId = 1,
                            Name_ARB = "شمال سيناء",
                            Name_ENG = "North Sinai"
                        },
                        new
                        {
                            Id = 22,
                            CountryId = 1,
                            Name_ARB = "جنوب سيناء",
                            Name_ENG = "South Sinai"
                        },
                        new
                        {
                            Id = 23,
                            CountryId = 1,
                            Name_ARB = "كفر الشيخ",
                            Name_ENG = "Kafr El Sheikh"
                        },
                        new
                        {
                            Id = 24,
                            CountryId = 1,
                            Name_ARB = "مطروح",
                            Name_ENG = "Matruh"
                        },
                        new
                        {
                            Id = 25,
                            CountryId = 1,
                            Name_ARB = "الأقصر",
                            Name_ENG = "Luxor"
                        },
                        new
                        {
                            Id = 26,
                            CountryId = 1,
                            Name_ARB = "قنا",
                            Name_ENG = "Qena"
                        },
                        new
                        {
                            Id = 27,
                            CountryId = 2,
                            Name_ARB = "الرياض",
                            Name_ENG = "Riyadh"
                        },
                        new
                        {
                            Id = 28,
                            CountryId = 2,
                            Name_ARB = "جدة",
                            Name_ENG = "Jeddah"
                        },
                        new
                        {
                            Id = 29,
                            CountryId = 2,
                            Name_ARB = "مكة المكرمة",
                            Name_ENG = "Mecca"
                        },
                        new
                        {
                            Id = 30,
                            CountryId = 2,
                            Name_ARB = "المدينة المنورة",
                            Name_ENG = "Medina"
                        },
                        new
                        {
                            Id = 31,
                            CountryId = 2,
                            Name_ARB = "الدمام",
                            Name_ENG = "Dammam"
                        },
                        new
                        {
                            Id = 32,
                            CountryId = 2,
                            Name_ARB = "الخبر",
                            Name_ENG = "Khobar"
                        },
                        new
                        {
                            Id = 33,
                            CountryId = 2,
                            Name_ARB = "أبها",
                            Name_ENG = "Abha"
                        },
                        new
                        {
                            Id = 34,
                            CountryId = 2,
                            Name_ARB = "تبوك",
                            Name_ENG = "Tabuk"
                        },
                        new
                        {
                            Id = 35,
                            CountryId = 2,
                            Name_ARB = "حائل",
                            Name_ENG = "Hail"
                        },
                        new
                        {
                            Id = 36,
                            CountryId = 2,
                            Name_ARB = "بريدة",
                            Name_ENG = "Buraidah"
                        },
                        new
                        {
                            Id = 37,
                            CountryId = 2,
                            Name_ARB = "نجران",
                            Name_ENG = "Najran"
                        },
                        new
                        {
                            Id = 38,
                            CountryId = 2,
                            Name_ARB = "جازان",
                            Name_ENG = "Jazan"
                        },
                        new
                        {
                            Id = 39,
                            CountryId = 2,
                            Name_ARB = "الباحة",
                            Name_ENG = "Al Bahah"
                        },
                        new
                        {
                            Id = 40,
                            CountryId = 3,
                            Name_ARB = "أبو ظبي",
                            Name_ENG = "Abu Dhabi"
                        },
                        new
                        {
                            Id = 41,
                            CountryId = 3,
                            Name_ARB = "دبي",
                            Name_ENG = "Dubai"
                        },
                        new
                        {
                            Id = 42,
                            CountryId = 3,
                            Name_ARB = "الشارقة",
                            Name_ENG = "Sharjah"
                        },
                        new
                        {
                            Id = 43,
                            CountryId = 3,
                            Name_ARB = "عجمان",
                            Name_ENG = "Ajman"
                        },
                        new
                        {
                            Id = 44,
                            CountryId = 3,
                            Name_ARB = "الفجيرة",
                            Name_ENG = "Fujairah"
                        },
                        new
                        {
                            Id = 45,
                            CountryId = 3,
                            Name_ARB = "أم القيوين",
                            Name_ENG = "Umm Al Quwain"
                        },
                        new
                        {
                            Id = 46,
                            CountryId = 3,
                            Name_ARB = "رأس الخيمة",
                            Name_ENG = "Ras Al Khaimah"
                        },
                        new
                        {
                            Id = 47,
                            CountryId = 4,
                            Name_ARB = "عمّان",
                            Name_ENG = "Amman"
                        },
                        new
                        {
                            Id = 48,
                            CountryId = 4,
                            Name_ARB = "إربد",
                            Name_ENG = "Irbid"
                        },
                        new
                        {
                            Id = 49,
                            CountryId = 4,
                            Name_ARB = "الزرقاء",
                            Name_ENG = "Zarqa"
                        },
                        new
                        {
                            Id = 50,
                            CountryId = 4,
                            Name_ARB = "العقبة",
                            Name_ENG = "Aqaba"
                        },
                        new
                        {
                            Id = 51,
                            CountryId = 4,
                            Name_ARB = "مأدبا",
                            Name_ENG = "Madaba"
                        },
                        new
                        {
                            Id = 52,
                            CountryId = 4,
                            Name_ARB = "جرش",
                            Name_ENG = "Jerash"
                        },
                        new
                        {
                            Id = 53,
                            CountryId = 4,
                            Name_ARB = "عجلون",
                            Name_ENG = "Ajloun"
                        },
                        new
                        {
                            Id = 54,
                            CountryId = 4,
                            Name_ARB = "المفرق",
                            Name_ENG = "Mafraq"
                        },
                        new
                        {
                            Id = 55,
                            CountryId = 4,
                            Name_ARB = "الكرك",
                            Name_ENG = "Karak"
                        },
                        new
                        {
                            Id = 56,
                            CountryId = 4,
                            Name_ARB = "الطفيلة",
                            Name_ENG = "Tafilah"
                        },
                        new
                        {
                            Id = 57,
                            CountryId = 4,
                            Name_ARB = "معان",
                            Name_ENG = "Ma'an"
                        },
                        new
                        {
                            Id = 58,
                            CountryId = 5,
                            Name_ARB = "بيروت",
                            Name_ENG = "Beirut"
                        },
                        new
                        {
                            Id = 59,
                            CountryId = 5,
                            Name_ARB = "طرابلس",
                            Name_ENG = "Tripoli"
                        },
                        new
                        {
                            Id = 60,
                            CountryId = 5,
                            Name_ARB = "صيدا",
                            Name_ENG = "Sidon"
                        },
                        new
                        {
                            Id = 61,
                            CountryId = 5,
                            Name_ARB = "صور",
                            Name_ENG = "Tyre"
                        },
                        new
                        {
                            Id = 62,
                            CountryId = 5,
                            Name_ARB = "زحلة",
                            Name_ENG = "Zahle"
                        },
                        new
                        {
                            Id = 63,
                            CountryId = 5,
                            Name_ARB = "جونية",
                            Name_ENG = "Jounieh"
                        },
                        new
                        {
                            Id = 64,
                            CountryId = 5,
                            Name_ARB = "جبيل",
                            Name_ENG = "Byblos"
                        },
                        new
                        {
                            Id = 65,
                            CountryId = 6,
                            Name_ARB = "دمشق",
                            Name_ENG = "Damascus"
                        },
                        new
                        {
                            Id = 66,
                            CountryId = 6,
                            Name_ARB = "حلب",
                            Name_ENG = "Aleppo"
                        },
                        new
                        {
                            Id = 67,
                            CountryId = 6,
                            Name_ARB = "حمص",
                            Name_ENG = "Homs"
                        },
                        new
                        {
                            Id = 68,
                            CountryId = 6,
                            Name_ARB = "اللاذقية",
                            Name_ENG = "Latakia"
                        },
                        new
                        {
                            Id = 69,
                            CountryId = 6,
                            Name_ARB = "طرطوس",
                            Name_ENG = "Tartus"
                        },
                        new
                        {
                            Id = 70,
                            CountryId = 6,
                            Name_ARB = "حماة",
                            Name_ENG = "Hama"
                        },
                        new
                        {
                            Id = 71,
                            CountryId = 6,
                            Name_ARB = "درعا",
                            Name_ENG = "Daraa"
                        },
                        new
                        {
                            Id = 72,
                            CountryId = 6,
                            Name_ARB = "دير الزور",
                            Name_ENG = "Deir ez-Zor"
                        },
                        new
                        {
                            Id = 73,
                            CountryId = 6,
                            Name_ARB = "الرقة",
                            Name_ENG = "Raqqa"
                        },
                        new
                        {
                            Id = 74,
                            CountryId = 6,
                            Name_ARB = "القنيطرة",
                            Name_ENG = "Quneitra"
                        },
                        new
                        {
                            Id = 75,
                            CountryId = 7,
                            Name_ARB = "بغداد",
                            Name_ENG = "Baghdad"
                        },
                        new
                        {
                            Id = 76,
                            CountryId = 7,
                            Name_ARB = "البصرة",
                            Name_ENG = "Basra"
                        },
                        new
                        {
                            Id = 77,
                            CountryId = 7,
                            Name_ARB = "الموصل",
                            Name_ENG = "Mosul"
                        },
                        new
                        {
                            Id = 78,
                            CountryId = 7,
                            Name_ARB = "أربيل",
                            Name_ENG = "Erbil"
                        },
                        new
                        {
                            Id = 79,
                            CountryId = 7,
                            Name_ARB = "كربلاء",
                            Name_ENG = "Karbala"
                        },
                        new
                        {
                            Id = 80,
                            CountryId = 7,
                            Name_ARB = "النجف",
                            Name_ENG = "Najaf"
                        },
                        new
                        {
                            Id = 81,
                            CountryId = 7,
                            Name_ARB = "كركوك",
                            Name_ENG = "Kirkuk"
                        },
                        new
                        {
                            Id = 82,
                            CountryId = 7,
                            Name_ARB = "السليمانية",
                            Name_ENG = "Sulaymaniyah"
                        },
                        new
                        {
                            Id = 83,
                            CountryId = 7,
                            Name_ARB = "ديالى",
                            Name_ENG = "Diyala"
                        },
                        new
                        {
                            Id = 84,
                            CountryId = 7,
                            Name_ARB = "ذي قار",
                            Name_ENG = "Dhi Qar"
                        },
                        new
                        {
                            Id = 85,
                            CountryId = 8,
                            Name_ARB = "القدس",
                            Name_ENG = "Jerusalem"
                        },
                        new
                        {
                            Id = 86,
                            CountryId = 8,
                            Name_ARB = "غزة",
                            Name_ENG = "Gaza"
                        },
                        new
                        {
                            Id = 87,
                            CountryId = 8,
                            Name_ARB = "الخليل",
                            Name_ENG = "Hebron"
                        },
                        new
                        {
                            Id = 88,
                            CountryId = 8,
                            Name_ARB = "نابلس",
                            Name_ENG = "Nablus"
                        },
                        new
                        {
                            Id = 89,
                            CountryId = 8,
                            Name_ARB = "بيت لحم",
                            Name_ENG = "Bethlehem"
                        },
                        new
                        {
                            Id = 90,
                            CountryId = 8,
                            Name_ARB = "رام الله",
                            Name_ENG = "Ramallah"
                        },
                        new
                        {
                            Id = 91,
                            CountryId = 8,
                            Name_ARB = "جنين",
                            Name_ENG = "Jenin"
                        },
                        new
                        {
                            Id = 92,
                            CountryId = 8,
                            Name_ARB = "طولكرم",
                            Name_ENG = "Tulkarm"
                        },
                        new
                        {
                            Id = 93,
                            CountryId = 8,
                            Name_ARB = "قلقيلية",
                            Name_ENG = "Qalqilya"
                        },
                        new
                        {
                            Id = 94,
                            CountryId = 8,
                            Name_ARB = "رفح",
                            Name_ENG = "Rafah"
                        },
                        new
                        {
                            Id = 95,
                            CountryId = 9,
                            Name_ARB = "الخرطوم",
                            Name_ENG = "Khartoum"
                        },
                        new
                        {
                            Id = 96,
                            CountryId = 9,
                            Name_ARB = "أم درمان",
                            Name_ENG = "Omdurman"
                        },
                        new
                        {
                            Id = 97,
                            CountryId = 9,
                            Name_ARB = "بورتسودان",
                            Name_ENG = "Port Sudan"
                        },
                        new
                        {
                            Id = 98,
                            CountryId = 9,
                            Name_ARB = "كسلا",
                            Name_ENG = "Kassala"
                        },
                        new
                        {
                            Id = 99,
                            CountryId = 9,
                            Name_ARB = "الأبيض",
                            Name_ENG = "El Obeid"
                        },
                        new
                        {
                            Id = 100,
                            CountryId = 9,
                            Name_ARB = "نيالا",
                            Name_ENG = "Nyala"
                        },
                        new
                        {
                            Id = 101,
                            CountryId = 9,
                            Name_ARB = "دنقلا",
                            Name_ENG = "Dongola"
                        },
                        new
                        {
                            Id = 102,
                            CountryId = 9,
                            Name_ARB = "الفاشر",
                            Name_ENG = "El Fasher"
                        },
                        new
                        {
                            Id = 103,
                            CountryId = 10,
                            Name_ARB = "طرابلس",
                            Name_ENG = "Tripoli"
                        },
                        new
                        {
                            Id = 104,
                            CountryId = 10,
                            Name_ARB = "بنغازي",
                            Name_ENG = "Benghazi"
                        },
                        new
                        {
                            Id = 105,
                            CountryId = 10,
                            Name_ARB = "مصراتة",
                            Name_ENG = "Misrata"
                        },
                        new
                        {
                            Id = 106,
                            CountryId = 10,
                            Name_ARB = "الزاوية",
                            Name_ENG = "Zawiya"
                        },
                        new
                        {
                            Id = 107,
                            CountryId = 10,
                            Name_ARB = "سبها",
                            Name_ENG = "Sabha"
                        },
                        new
                        {
                            Id = 108,
                            CountryId = 10,
                            Name_ARB = "درنة",
                            Name_ENG = "Derna"
                        },
                        new
                        {
                            Id = 109,
                            CountryId = 10,
                            Name_ARB = "طبرق",
                            Name_ENG = "Tobruk"
                        },
                        new
                        {
                            Id = 110,
                            CountryId = 10,
                            Name_ARB = "البيضاء",
                            Name_ENG = "Al Bayda"
                        },
                        new
                        {
                            Id = 111,
                            CountryId = 11,
                            Name_ARB = "تونس",
                            Name_ENG = "Tunis"
                        },
                        new
                        {
                            Id = 112,
                            CountryId = 11,
                            Name_ARB = "صفاقس",
                            Name_ENG = "Sfax"
                        },
                        new
                        {
                            Id = 113,
                            CountryId = 11,
                            Name_ARB = "سوسة",
                            Name_ENG = "Sousse"
                        },
                        new
                        {
                            Id = 114,
                            CountryId = 11,
                            Name_ARB = "القيروان",
                            Name_ENG = "Kairouan"
                        },
                        new
                        {
                            Id = 115,
                            CountryId = 11,
                            Name_ARB = "بنزرت",
                            Name_ENG = "Bizerte"
                        },
                        new
                        {
                            Id = 116,
                            CountryId = 11,
                            Name_ARB = "قابس",
                            Name_ENG = "Gabes"
                        },
                        new
                        {
                            Id = 117,
                            CountryId = 11,
                            Name_ARB = "قفصة",
                            Name_ENG = "Gafsa"
                        },
                        new
                        {
                            Id = 118,
                            CountryId = 11,
                            Name_ARB = "المنستير",
                            Name_ENG = "Monastir"
                        },
                        new
                        {
                            Id = 119,
                            CountryId = 11,
                            Name_ARB = "نابل",
                            Name_ENG = "Nabeul"
                        },
                        new
                        {
                            Id = 120,
                            CountryId = 11,
                            Name_ARB = "سيدي بوزيد",
                            Name_ENG = "Sidi Bouzid"
                        },
                        new
                        {
                            Id = 121,
                            CountryId = 11,
                            Name_ARB = "قصرين",
                            Name_ENG = "Kasserine"
                        },
                        new
                        {
                            Id = 122,
                            CountryId = 11,
                            Name_ARB = "جندوبة",
                            Name_ENG = "Jendouba"
                        },
                        new
                        {
                            Id = 123,
                            CountryId = 11,
                            Name_ARB = "سليانة",
                            Name_ENG = "Siliana"
                        },
                        new
                        {
                            Id = 124,
                            CountryId = 11,
                            Name_ARB = "توزر",
                            Name_ENG = "Tozeur"
                        },
                        new
                        {
                            Id = 125,
                            CountryId = 11,
                            Name_ARB = "مدنين",
                            Name_ENG = "Medenine"
                        },
                        new
                        {
                            Id = 126,
                            CountryId = 11,
                            Name_ARB = "المهدية",
                            Name_ENG = "Mahdia"
                        },
                        new
                        {
                            Id = 127,
                            CountryId = 11,
                            Name_ARB = "قبلي",
                            Name_ENG = "Kebili"
                        },
                        new
                        {
                            Id = 128,
                            CountryId = 11,
                            Name_ARB = "أريانة",
                            Name_ENG = "Ariana"
                        },
                        new
                        {
                            Id = 129,
                            CountryId = 11,
                            Name_ARB = "بن عروس",
                            Name_ENG = "Ben Arous"
                        },
                        new
                        {
                            Id = 130,
                            CountryId = 11,
                            Name_ARB = "منوبة",
                            Name_ENG = "Manouba"
                        },
                        new
                        {
                            Id = 131,
                            CountryId = 11,
                            Name_ARB = "الكاف",
                            Name_ENG = "Kef"
                        },
                        new
                        {
                            Id = 132,
                            CountryId = 11,
                            Name_ARB = "تطاوين",
                            Name_ENG = "Tataouine"
                        },
                        new
                        {
                            Id = 133,
                            CountryId = 11,
                            Name_ARB = "زغوان",
                            Name_ENG = "Zaghouan"
                        },
                        new
                        {
                            Id = 134,
                            CountryId = 12,
                            Name_ARB = "الجزائر العاصمة",
                            Name_ENG = "Algiers"
                        },
                        new
                        {
                            Id = 135,
                            CountryId = 12,
                            Name_ARB = "وهران",
                            Name_ENG = "Oran"
                        },
                        new
                        {
                            Id = 136,
                            CountryId = 12,
                            Name_ARB = "قسنطينة",
                            Name_ENG = "Constantine"
                        },
                        new
                        {
                            Id = 137,
                            CountryId = 12,
                            Name_ARB = "عنابة",
                            Name_ENG = "Annaba"
                        },
                        new
                        {
                            Id = 138,
                            CountryId = 12,
                            Name_ARB = "البليدة",
                            Name_ENG = "Blida"
                        },
                        new
                        {
                            Id = 139,
                            CountryId = 12,
                            Name_ARB = "سطيف",
                            Name_ENG = "Setif"
                        },
                        new
                        {
                            Id = 140,
                            CountryId = 12,
                            Name_ARB = "باتنة",
                            Name_ENG = "Batna"
                        },
                        new
                        {
                            Id = 141,
                            CountryId = 12,
                            Name_ARB = "تلمسان",
                            Name_ENG = "Tlemcen"
                        },
                        new
                        {
                            Id = 142,
                            CountryId = 12,
                            Name_ARB = "سيدي بلعباس",
                            Name_ENG = "Sidi Bel Abbes"
                        },
                        new
                        {
                            Id = 143,
                            CountryId = 12,
                            Name_ARB = "بسكرة",
                            Name_ENG = "Biskra"
                        },
                        new
                        {
                            Id = 144,
                            CountryId = 12,
                            Name_ARB = "تيزي وزو",
                            Name_ENG = "Tizi Ouzou"
                        },
                        new
                        {
                            Id = 145,
                            CountryId = 12,
                            Name_ARB = "بجاية",
                            Name_ENG = "Bejaia"
                        },
                        new
                        {
                            Id = 146,
                            CountryId = 12,
                            Name_ARB = "الجلفة",
                            Name_ENG = "Djelfa"
                        },
                        new
                        {
                            Id = 147,
                            CountryId = 12,
                            Name_ARB = "معسكر",
                            Name_ENG = "Mascara"
                        },
                        new
                        {
                            Id = 148,
                            CountryId = 12,
                            Name_ARB = "بشار",
                            Name_ENG = "Bechar"
                        },
                        new
                        {
                            Id = 149,
                            CountryId = 12,
                            Name_ARB = "تمنراست",
                            Name_ENG = "Tamanrasset"
                        },
                        new
                        {
                            Id = 150,
                            CountryId = 13,
                            Name_ARB = "الرباط",
                            Name_ENG = "Rabat"
                        },
                        new
                        {
                            Id = 151,
                            CountryId = 13,
                            Name_ARB = "الدار البيضاء",
                            Name_ENG = "Casablanca"
                        },
                        new
                        {
                            Id = 152,
                            CountryId = 13,
                            Name_ARB = "فاس",
                            Name_ENG = "Fes"
                        },
                        new
                        {
                            Id = 153,
                            CountryId = 13,
                            Name_ARB = "مراكش",
                            Name_ENG = "Marrakesh"
                        },
                        new
                        {
                            Id = 154,
                            CountryId = 13,
                            Name_ARB = "طنجة",
                            Name_ENG = "Tangier"
                        },
                        new
                        {
                            Id = 155,
                            CountryId = 13,
                            Name_ARB = "أكادير",
                            Name_ENG = "Agadir"
                        },
                        new
                        {
                            Id = 156,
                            CountryId = 13,
                            Name_ARB = "وجدة",
                            Name_ENG = "Oujda"
                        },
                        new
                        {
                            Id = 157,
                            CountryId = 13,
                            Name_ARB = "القنيطرة",
                            Name_ENG = "Kenitra"
                        },
                        new
                        {
                            Id = 158,
                            CountryId = 13,
                            Name_ARB = "مكناس",
                            Name_ENG = "Meknes"
                        },
                        new
                        {
                            Id = 159,
                            CountryId = 13,
                            Name_ARB = "تطوان",
                            Name_ENG = "Tetouan"
                        },
                        new
                        {
                            Id = 160,
                            CountryId = 13,
                            Name_ARB = "آسفي",
                            Name_ENG = "Safi"
                        },
                        new
                        {
                            Id = 161,
                            CountryId = 13,
                            Name_ARB = "الجديدة",
                            Name_ENG = "El Jadida"
                        },
                        new
                        {
                            Id = 162,
                            CountryId = 13,
                            Name_ARB = "بني ملال",
                            Name_ENG = "Beni Mellal"
                        },
                        new
                        {
                            Id = 163,
                            CountryId = 13,
                            Name_ARB = "الناظور",
                            Name_ENG = "Nador"
                        },
                        new
                        {
                            Id = 164,
                            CountryId = 13,
                            Name_ARB = "تازة",
                            Name_ENG = "Taza"
                        },
                        new
                        {
                            Id = 165,
                            CountryId = 14,
                            Name_ARB = "نواكشوط",
                            Name_ENG = "Nouakchott"
                        },
                        new
                        {
                            Id = 166,
                            CountryId = 14,
                            Name_ARB = "نواذيبو",
                            Name_ENG = "Nouadhibou"
                        },
                        new
                        {
                            Id = 167,
                            CountryId = 14,
                            Name_ARB = "زويرات",
                            Name_ENG = "Zouérat"
                        },
                        new
                        {
                            Id = 168,
                            CountryId = 14,
                            Name_ARB = "أطار",
                            Name_ENG = "Atar"
                        },
                        new
                        {
                            Id = 169,
                            CountryId = 14,
                            Name_ARB = "كيهيدي",
                            Name_ENG = "Kaédi"
                        },
                        new
                        {
                            Id = 170,
                            CountryId = 14,
                            Name_ARB = "كيفه",
                            Name_ENG = "Kiffa"
                        },
                        new
                        {
                            Id = 171,
                            CountryId = 14,
                            Name_ARB = "روصو",
                            Name_ENG = "Rosso"
                        },
                        new
                        {
                            Id = 172,
                            CountryId = 14,
                            Name_ARB = "تجكجه",
                            Name_ENG = "Tidjikja"
                        },
                        new
                        {
                            Id = 173,
                            CountryId = 14,
                            Name_ARB = "ألاك",
                            Name_ENG = "Aleg"
                        },
                        new
                        {
                            Id = 174,
                            CountryId = 14,
                            Name_ARB = "سيليبابي",
                            Name_ENG = "Sélibaby"
                        },
                        new
                        {
                            Id = 175,
                            CountryId = 14,
                            Name_ARB = "النعمة",
                            Name_ENG = "Néma"
                        },
                        new
                        {
                            Id = 176,
                            CountryId = 15,
                            Name_ARB = "مقديشو",
                            Name_ENG = "Mogadishu"
                        },
                        new
                        {
                            Id = 177,
                            CountryId = 15,
                            Name_ARB = "هرجيسا",
                            Name_ENG = "Hargeisa"
                        },
                        new
                        {
                            Id = 178,
                            CountryId = 15,
                            Name_ARB = "بوصاصو",
                            Name_ENG = "Bosaso"
                        },
                        new
                        {
                            Id = 179,
                            CountryId = 15,
                            Name_ARB = "كيسمايو",
                            Name_ENG = "Kismayo"
                        },
                        new
                        {
                            Id = 180,
                            CountryId = 15,
                            Name_ARB = "بيدوا",
                            Name_ENG = "Baidoa"
                        },
                        new
                        {
                            Id = 181,
                            CountryId = 15,
                            Name_ARB = "جالكعيو",
                            Name_ENG = "Galkayo"
                        },
                        new
                        {
                            Id = 182,
                            CountryId = 15,
                            Name_ARB = "غرووي",
                            Name_ENG = "Garowe"
                        },
                        new
                        {
                            Id = 183,
                            CountryId = 15,
                            Name_ARB = "بلد وين",
                            Name_ENG = "Beledweyne"
                        },
                        new
                        {
                            Id = 184,
                            CountryId = 15,
                            Name_ARB = "مركا",
                            Name_ENG = "Marka"
                        },
                        new
                        {
                            Id = 185,
                            CountryId = 15,
                            Name_ARB = "جوهار",
                            Name_ENG = "Jowhar"
                        },
                        new
                        {
                            Id = 186,
                            CountryId = 15,
                            Name_ARB = "أفجوي",
                            Name_ENG = "Afgooye"
                        },
                        new
                        {
                            Id = 187,
                            CountryId = 16,
                            Name_ARB = "جيبوتي",
                            Name_ENG = "Djibouti"
                        },
                        new
                        {
                            Id = 188,
                            CountryId = 16,
                            Name_ARB = "علي صبيح",
                            Name_ENG = "Ali Sabieh"
                        },
                        new
                        {
                            Id = 189,
                            CountryId = 16,
                            Name_ARB = "تاجورة",
                            Name_ENG = "Tadjourah"
                        },
                        new
                        {
                            Id = 190,
                            CountryId = 16,
                            Name_ARB = "أوبوك",
                            Name_ENG = "Obock"
                        },
                        new
                        {
                            Id = 191,
                            CountryId = 16,
                            Name_ARB = "دخيل",
                            Name_ENG = "Dikhil"
                        },
                        new
                        {
                            Id = 192,
                            CountryId = 16,
                            Name_ARB = "أرتا",
                            Name_ENG = "Arta"
                        },
                        new
                        {
                            Id = 193,
                            CountryId = 17,
                            Name_ARB = "موروني",
                            Name_ENG = "Moroni"
                        },
                        new
                        {
                            Id = 194,
                            CountryId = 17,
                            Name_ARB = "متسامودو",
                            Name_ENG = "Mutsamudu"
                        },
                        new
                        {
                            Id = 195,
                            CountryId = 17,
                            Name_ARB = "فمبوني",
                            Name_ENG = "Fomboni"
                        },
                        new
                        {
                            Id = 196,
                            CountryId = 17,
                            Name_ARB = "دوموني",
                            Name_ENG = "Domoni"
                        },
                        new
                        {
                            Id = 197,
                            CountryId = 17,
                            Name_ARB = "واني",
                            Name_ENG = "Ouani"
                        },
                        new
                        {
                            Id = 198,
                            CountryId = 18,
                            Name_ARB = "صنعاء",
                            Name_ENG = "Sana'a"
                        },
                        new
                        {
                            Id = 199,
                            CountryId = 18,
                            Name_ARB = "عدن",
                            Name_ENG = "Aden"
                        },
                        new
                        {
                            Id = 200,
                            CountryId = 18,
                            Name_ARB = "تعز",
                            Name_ENG = "Taiz"
                        },
                        new
                        {
                            Id = 201,
                            CountryId = 18,
                            Name_ARB = "إب",
                            Name_ENG = "Ibb"
                        },
                        new
                        {
                            Id = 202,
                            CountryId = 18,
                            Name_ARB = "الحديدة",
                            Name_ENG = "Al Hudaydah"
                        },
                        new
                        {
                            Id = 203,
                            CountryId = 18,
                            Name_ARB = "حضرموت",
                            Name_ENG = "Hadramout"
                        },
                        new
                        {
                            Id = 204,
                            CountryId = 19,
                            Name_ARB = "المنامة",
                            Name_ENG = "Manama"
                        },
                        new
                        {
                            Id = 205,
                            CountryId = 19,
                            Name_ARB = "المحرق",
                            Name_ENG = "Muharraq"
                        },
                        new
                        {
                            Id = 206,
                            CountryId = 19,
                            Name_ARB = "الرفاع",
                            Name_ENG = "Riffa"
                        },
                        new
                        {
                            Id = 207,
                            CountryId = 19,
                            Name_ARB = "مدينة عيسى",
                            Name_ENG = "Isa Town"
                        },
                        new
                        {
                            Id = 208,
                            CountryId = 19,
                            Name_ARB = "مدينة حمد",
                            Name_ENG = "Hamad Town"
                        },
                        new
                        {
                            Id = 209,
                            CountryId = 20,
                            Name_ARB = "الدوحة",
                            Name_ENG = "Doha"
                        },
                        new
                        {
                            Id = 210,
                            CountryId = 20,
                            Name_ARB = "الريان",
                            Name_ENG = "Al Rayyan"
                        },
                        new
                        {
                            Id = 211,
                            CountryId = 20,
                            Name_ARB = "أم صلال",
                            Name_ENG = "Umm Salal"
                        },
                        new
                        {
                            Id = 212,
                            CountryId = 20,
                            Name_ARB = "الوكرة",
                            Name_ENG = "Al Wakrah"
                        },
                        new
                        {
                            Id = 213,
                            CountryId = 20,
                            Name_ARB = "الخور",
                            Name_ENG = "Al Khor"
                        },
                        new
                        {
                            Id = 214,
                            CountryId = 21,
                            Name_ARB = "مسقط",
                            Name_ENG = "Muscat"
                        },
                        new
                        {
                            Id = 215,
                            CountryId = 21,
                            Name_ARB = "صلالة",
                            Name_ENG = "Salalah"
                        },
                        new
                        {
                            Id = 216,
                            CountryId = 21,
                            Name_ARB = "صحار",
                            Name_ENG = "Sohar"
                        },
                        new
                        {
                            Id = 217,
                            CountryId = 21,
                            Name_ARB = "نزوى",
                            Name_ENG = "Nizwa"
                        },
                        new
                        {
                            Id = 218,
                            CountryId = 21,
                            Name_ARB = "صور",
                            Name_ENG = "Sur"
                        },
                        new
                        {
                            Id = 219,
                            CountryId = 22,
                            Name_ARB = "مدينة الكويت",
                            Name_ENG = "Kuwait City"
                        },
                        new
                        {
                            Id = 220,
                            CountryId = 22,
                            Name_ARB = "الأحمدي",
                            Name_ENG = "Al Ahmadi"
                        },
                        new
                        {
                            Id = 221,
                            CountryId = 22,
                            Name_ARB = "حولي",
                            Name_ENG = "Hawalli"
                        },
                        new
                        {
                            Id = 222,
                            CountryId = 22,
                            Name_ARB = "الفروانية",
                            Name_ENG = "Farwaniya"
                        },
                        new
                        {
                            Id = 223,
                            CountryId = 22,
                            Name_ARB = "الجهراء",
                            Name_ENG = "Jahra"
                        },
                        new
                        {
                            Id = 224,
                            CountryId = 22,
                            Name_ARB = "مبارك الكبير",
                            Name_ENG = "Mubarak Al-Kabeer"
                        });
                });

            modelBuilder.Entity("IslamicFace.Domain.Entities.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("Int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name_ARB")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR");

                    b.Property<string>("Name_ENG")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("VARCHAR");

                    b.HasKey("Id");

                    b.ToTable("Countries", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name_ARB = "مصر",
                            Name_ENG = "Egypt"
                        },
                        new
                        {
                            Id = 2,
                            Name_ARB = "السعودية",
                            Name_ENG = "Saudi Arabia"
                        },
                        new
                        {
                            Id = 3,
                            Name_ARB = "الإمارات",
                            Name_ENG = "United Arab Emirates"
                        },
                        new
                        {
                            Id = 4,
                            Name_ARB = "الأردن",
                            Name_ENG = "Jordan"
                        },
                        new
                        {
                            Id = 5,
                            Name_ARB = "لبنان",
                            Name_ENG = "Lebanon"
                        },
                        new
                        {
                            Id = 6,
                            Name_ARB = "سوريا",
                            Name_ENG = "Syria"
                        },
                        new
                        {
                            Id = 7,
                            Name_ARB = "العراق",
                            Name_ENG = "Iraq"
                        },
                        new
                        {
                            Id = 8,
                            Name_ARB = "فلسطين",
                            Name_ENG = "Palestine"
                        },
                        new
                        {
                            Id = 9,
                            Name_ARB = "السودان",
                            Name_ENG = "Sudan"
                        },
                        new
                        {
                            Id = 10,
                            Name_ARB = "ليبيا",
                            Name_ENG = "Libya"
                        },
                        new
                        {
                            Id = 11,
                            Name_ARB = "تونس",
                            Name_ENG = "Tunisia"
                        },
                        new
                        {
                            Id = 12,
                            Name_ARB = "الجزائر",
                            Name_ENG = "Algeria"
                        },
                        new
                        {
                            Id = 13,
                            Name_ARB = "المغرب",
                            Name_ENG = "Morocco"
                        },
                        new
                        {
                            Id = 14,
                            Name_ARB = "موريتانيا",
                            Name_ENG = "Mauritania"
                        },
                        new
                        {
                            Id = 15,
                            Name_ARB = "الصومال",
                            Name_ENG = "Somalia"
                        },
                        new
                        {
                            Id = 16,
                            Name_ARB = "جيبوتي",
                            Name_ENG = "Djibouti"
                        },
                        new
                        {
                            Id = 17,
                            Name_ARB = "جزر القمر",
                            Name_ENG = "Comoros"
                        },
                        new
                        {
                            Id = 18,
                            Name_ARB = "اليمن",
                            Name_ENG = "Yemen"
                        },
                        new
                        {
                            Id = 19,
                            Name_ARB = "البحرين",
                            Name_ENG = "Bahrain"
                        },
                        new
                        {
                            Id = 20,
                            Name_ARB = "قطر",
                            Name_ENG = "Qatar"
                        },
                        new
                        {
                            Id = 21,
                            Name_ARB = "عمان",
                            Name_ENG = "Oman"
                        },
                        new
                        {
                            Id = 22,
                            Name_ARB = "الكويت",
                            Name_ENG = "Kuwait"
                        });
                });

            modelBuilder.Entity("IslamicFace.Domain.Entities.FriendRequest", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("BigInt");

                    b.Property<DateTime>("DateSend")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DateTime")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<Guid>("ReceiverID")
                        .HasColumnType("UNIQUEIDENTIFIER");

                    b.Property<byte>("RequestStatus")
                        .HasColumnType("TinyInt");

                    b.Property<DateTime?>("ResponseAt")
                        .HasColumnType("DateTime");

                    b.Property<Guid>("senderID")
                        .HasColumnType("UNIQUEIDENTIFIER");

                    b.HasKey("Id")
                        .HasAnnotation("SqlServer:Identity", "1, 1");

                    b.HasIndex("ReceiverID");

                    b.HasIndex("senderID", "ReceiverID")
                        .IsUnique();

                    b.ToTable("FriendRequests", (string)null);
                });

            modelBuilder.Entity("IslamicFace.Domain.Entities.Post", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("BigInt");

                    b.Property<DateTime>("createdAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DateTime")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("postText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("VARCHAR");

                    b.Property<Guid>("userId")
                        .HasColumnType("UNIQUEIDENTIFIER");

                    b.HasKey("Id")
                        .HasAnnotation("SqlServer:Identity", "1, 1");

                    b.HasIndex("userId");

                    b.ToTable("Posts", (string)null);
                });

            modelBuilder.Entity("IslamicFace.Domain.Entities.PostComment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BigInt");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Comment")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR");

                    b.Property<long?>("ParentCommentID")
                        .HasColumnType("BigInt");

                    b.Property<DateTime>("createdAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DateTime")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<long>("postId")
                        .HasColumnType("BigInt");

                    b.Property<int>("reactLikeCount")
                        .HasColumnType("int");

                    b.Property<Guid>("userId")
                        .HasColumnType("UNIQUEIDENTIFIER");

                    b.HasKey("Id")
                        .HasAnnotation("SqlServer:Identity", "1, 1");

                    b.HasIndex("ParentCommentID");

                    b.HasIndex("postId");

                    b.HasIndex("userId");

                    b.ToTable("PostComments", (string)null);
                });

            modelBuilder.Entity("IslamicFace.Domain.Entities.PostMedia", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("BigInt");

                    b.Property<byte>("mediaType")
                        .HasColumnType("tinyInt");

                    b.Property<string>("mediaURL")
                        .IsRequired()
                        .HasMaxLength(2083)
                        .HasColumnType("VARCHAR");

                    b.Property<long>("postId")
                        .HasColumnType("BigInt");

                    b.HasKey("Id")
                        .HasAnnotation("SqlServer:Identity", "1, 1");

                    b.HasIndex("postId");

                    b.ToTable("PostMedias", (string)null);
                });

            modelBuilder.Entity("IslamicFace.Domain.Entities.PostReaction", b =>
                {
                    b.Property<Guid>("userId")
                        .HasColumnType("UNIQUEIDENTIFIER");

                    b.Property<long>("postId")
                        .HasColumnType("BigInt");

                    b.Property<byte>("reactTypeID")
                        .HasColumnType("TinyInt");

                    b.HasKey("userId", "postId");

                    b.HasIndex("postId");

                    b.HasIndex("reactTypeID")
                        .IsUnique();

                    b.ToTable("PostReactions", (string)null);
                });

            modelBuilder.Entity("IslamicFace.Domain.Entities.PostTag", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("BigInt");

                    b.Property<long>("postId")
                        .HasColumnType("BigInt");

                    b.Property<string>("tag")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR");

                    b.HasKey("Id")
                        .HasAnnotation("SqlServer:Identity", "1, 1");

                    b.HasIndex("postId");

                    b.ToTable("PostTags", (string)null);
                });

            modelBuilder.Entity("IslamicFace.Domain.Entities.Reaction", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnType("TinyInt");

                    b.Property<string>("ReactType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasAnnotation("SqlServer:Identity", "1, 1");

                    b.ToTable("Reactions", (string)null);
                });

            modelBuilder.Entity("IslamicFace.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("UNIQUEIDENTIFIER");

                    b.Property<string>("bio")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("VARCHAR");

                    b.Property<int>("cityID")
                        .HasColumnType("Int");

                    b.Property<int>("countryID")
                        .HasColumnType("Int");

                    b.Property<DateOnly>("dateOfBirth")
                        .HasColumnType("Date");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("VARCHAR");

                    b.Property<bool>("gender")
                        .HasColumnType("Bit");

                    b.Property<DateTime>("joinDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DateTime")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("profilePictureURL")
                        .IsRequired()
                        .HasMaxLength(2083)
                        .HasColumnType("VARCHAR");

                    b.Property<byte>("settingId")
                        .HasColumnType("TinyInt");

                    b.Property<string>("userName")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("VARCHAR");

                    b.Property<byte>("userType")
                        .HasColumnType("TinyInt");

                    b.HasKey("Id");

                    b.HasIndex("countryID")
                        .IsUnique();

                    b.HasIndex("settingId")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("IslamicFace.Domain.Entities.UserSetting", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnType("TinyInt");

                    b.Property<string>("GenderOfFriends")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasAnnotation("SqlServer:Identity", "1, 1");

                    b.ToTable("UserSettings", (string)null);

                    b.HasData(
                        new
                        {
                            Id = (byte)1,
                            GenderOfFriends = "Male"
                        },
                        new
                        {
                            Id = (byte)2,
                            GenderOfFriends = "Female"
                        },
                        new
                        {
                            Id = (byte)3,
                            GenderOfFriends = "Both"
                        });
                });

            modelBuilder.Entity("IslamicFace.Domain.Entities.City", b =>
                {
                    b.HasOne("IslamicFace.Domain.Entities.Country", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("IslamicFace.Domain.Entities.FriendRequest", b =>
                {
                    b.HasOne("IslamicFace.Domain.Entities.User", "Receiver")
                        .WithMany("RecoversRequests")
                        .HasForeignKey("ReceiverID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("IslamicFace.Domain.Entities.User", "Sender")
                        .WithMany("senderRequests")
                        .HasForeignKey("senderID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("IslamicFace.Domain.Entities.Post", b =>
                {
                    b.HasOne("IslamicFace.Domain.Entities.User", "User")
                        .WithMany("Posts")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("IslamicFace.Domain.Entities.PostComment", b =>
                {
                    b.HasOne("IslamicFace.Domain.Entities.PostComment", "comment")
                        .WithMany("Post_Comments")
                        .HasForeignKey("ParentCommentID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("IslamicFace.Domain.Entities.Post", "Post")
                        .WithMany("PostComments")
                        .HasForeignKey("postId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IslamicFace.Domain.Entities.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("User");

                    b.Navigation("comment");
                });

            modelBuilder.Entity("IslamicFace.Domain.Entities.PostMedia", b =>
                {
                    b.HasOne("IslamicFace.Domain.Entities.Post", "Post")
                        .WithMany("PostMedias")
                        .HasForeignKey("postId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("IslamicFace.Domain.Entities.PostReaction", b =>
                {
                    b.HasOne("IslamicFace.Domain.Entities.Post", "Post")
                        .WithMany("PostReactions")
                        .HasForeignKey("postId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IslamicFace.Domain.Entities.Reaction", "Reaction")
                        .WithOne("PostReaction")
                        .HasForeignKey("IslamicFace.Domain.Entities.PostReaction", "reactTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IslamicFace.Domain.Entities.User", "User")
                        .WithMany("PostReactions")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("Reaction");

                    b.Navigation("User");
                });

            modelBuilder.Entity("IslamicFace.Domain.Entities.PostTag", b =>
                {
                    b.HasOne("IslamicFace.Domain.Entities.Post", "Post")
                        .WithMany("PostTags")
                        .HasForeignKey("postId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("IslamicFace.Domain.Entities.User", b =>
                {
                    b.HasOne("IslamicFace.Domain.Entities.Country", "Country")
                        .WithOne("User")
                        .HasForeignKey("IslamicFace.Domain.Entities.User", "countryID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IslamicFace.Domain.Entities.UserSetting", "UserSetting")
                        .WithOne("User")
                        .HasForeignKey("IslamicFace.Domain.Entities.User", "settingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Country");

                    b.Navigation("UserSetting");
                });

            modelBuilder.Entity("IslamicFace.Domain.Entities.Country", b =>
                {
                    b.Navigation("Cities");

                    b.Navigation("User");
                });

            modelBuilder.Entity("IslamicFace.Domain.Entities.Post", b =>
                {
                    b.Navigation("PostComments");

                    b.Navigation("PostMedias");

                    b.Navigation("PostReactions");

                    b.Navigation("PostTags");
                });

            modelBuilder.Entity("IslamicFace.Domain.Entities.PostComment", b =>
                {
                    b.Navigation("Post_Comments");
                });

            modelBuilder.Entity("IslamicFace.Domain.Entities.Reaction", b =>
                {
                    b.Navigation("PostReaction");
                });

            modelBuilder.Entity("IslamicFace.Domain.Entities.User", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("PostReactions");

                    b.Navigation("Posts");

                    b.Navigation("RecoversRequests");

                    b.Navigation("senderRequests");
                });

            modelBuilder.Entity("IslamicFace.Domain.Entities.UserSetting", b =>
                {
                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
